// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtv1pAJqSKKXv3J7BcR5SoP7dx1bU3GcI',
    appId: '1:675211764618:web:7b2ceb23dd3531459d5e73',
    messagingSenderId: '675211764618',
    projectId: 'sketchmage-fc268',
    authDomain: 'sketchmage-fc268.firebaseapp.com',
    storageBucket: 'sketchmage-fc268.firebasestorage.app',
    measurementId: 'G-R8F5N47VT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfx5tbtW6mXK__mRK1aEySonXL4PXonEY',
    appId: '1:675211764618:android:049c73053d4d81459d5e73',
    messagingSenderId: '675211764618',
    projectId: 'sketchmage-fc268',
    storageBucket: 'sketchmage-fc268.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHTWyaP4LVk4MfyVCq1MVvculpCq8erVw',
    appId: '1:675211764618:ios:de0ff600c36c02e19d5e73',
    messagingSenderId: '675211764618',
    projectId: 'sketchmage-fc268',
    storageBucket: 'sketchmage-fc268.firebasestorage.app',
    iosBundleId: 'com.example.sketchmage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHTWyaP4LVk4MfyVCq1MVvculpCq8erVw',
    appId: '1:675211764618:ios:de0ff600c36c02e19d5e73',
    messagingSenderId: '675211764618',
    projectId: 'sketchmage-fc268',
    storageBucket: 'sketchmage-fc268.firebasestorage.app',
    iosBundleId: 'com.example.sketchmage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtv1pAJqSKKXv3J7BcR5SoP7dx1bU3GcI',
    appId: '1:675211764618:web:04ff36798d68f3069d5e73',
    messagingSenderId: '675211764618',
    projectId: 'sketchmage-fc268',
    authDomain: 'sketchmage-fc268.firebaseapp.com',
    storageBucket: 'sketchmage-fc268.firebasestorage.app',
    measurementId: 'G-4RQMNQCM0J',
  );
}
